### ISSUE TITLE
Find a way of computing lazy expressions in Javascript, or drop laziness completely

### ISSUE THREAD

**Issue by 0x0f0f0f** [0x0f0f0f/minicaml#3]

**Comment by klntsky** [comment]
You can defer them (represent `a` as a function `() -> a`).

Like purescript does: https://pursuit.purescript.org/packages/purescript-control/4.2.0/docs/Control.Lazy#t:Lazy

**Comment by 0x0f0f0f** [comment]
Closing because webassembly will be a preferable target over Javascript
