### ISSUE TITLE
Should types representing functions to be moved to a single-argument nested style?

### ISSUE THREAD

**Issue by 0x0f0f0f** [0x0f0f0f/minicaml#7]
Should the definition for function expressions be like this
```ocaml
type expr = 
...
| Lambda of ide * expr
```
so that a function that takes 3 arguments becomes `(Lambda ("x", (Lambda ("y", Lambda ("z", ...body...))))`

Or should i keep the list style?
```ocaml
type expr = 
...
| Lambda of ide list * expr
```
where a function that takes 3 arguments is 
`(Lambda (["x"; "y"; "z"], ...body...)`

I think the latter is easier to read, but the first one makes currying and static type inference easier.

**Comment by jasoncarr0** [comment]
One potential effect is that the latter as written will distinguish the definitions:
```
f x = fun y => e
f x y = e
```
Specifically, this means that if a choice is made based on syntactic saturatedness, then these two definitions have distinct intrinsic behavior. If this is undesirable, then the first representation or normalization should be used.

**Comment by cheery** [comment]
Do the first one if you're doing ocaml-style language. If you'll optimize lambdas by clumping them together, it'll be likely in this way: `x → y → z → body` ==>> `(x ∧ y ∧ z) → body`, not by RLE-encoding original structures.

**Comment by 0x0f0f0f** [comment]
Chose the first one. Closing. A lot of things like partial application now snap together nicely. Thank you!
